defaults: &DEFAULT
  working_directory: /home/circleci/xblock-html
  docker:
    - image: circleci/python:2.7


version: 2
jobs:
  build:
    <<: *DEFAULT
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/circle.txt" }}
      - run:
          name: Installing requirements
          command: |
            virtualenv env
            source env/bin/activate
            pip install -r requirements/circle.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/circle.txt" }}
          paths:
            - env
      - persist_to_workspace:
          # this is done to persist virtualenv across workflows 
          root: .
          paths:
            - env

  test:
    <<: *DEFAULT
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/xblock-html
      - run:
          name: Activate virtualenv
          command: echo 'source env/bin/activate' >> $BASH_ENV
      - run:
          name: Running tests
          command: tox
      - run:
          name: Test Quality
          command: TOXENV=quality && tox
      - run:
          name: Generating code coverage
          command: codecov

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
